GET http://127.0.0.1:8000/health

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What are Katherine's customers that have a RR hold?"
}

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What are the NBAs for 2Seventy BIO and who is the account owner?"
}