GET http://127.0.0.1:8000/health

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What are the other accounts owned by Melissa?"
}
###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What is velocity?."
}