GET http://127.0.0.1:8000/health

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What are the accounts for Melissa.  Show the NBAs for each of her accounts?"
}

###

POST http://127.0.0.1:8000/chat
Content-Type: application/json

{
  "user": "testuser",
  "message": "What are the NBAs for 2Seventy BIO and who is the account owner?"
}